import type { Metadata } from "next"
import { Readex_Pro } from "next/font/google"
import "./globals.css"
import Web3ModalProvider from "@/providers/Web3ModalProvider"
import Navbar from "@/components/shared/Navbar/Navbar"
import Sidebar from "@/components/shared/Sidebar/Sidebar"

// Importing the Readex Pro font
const readexPro = Readex_Pro({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${readexPro.className}   max-w-[1730px] mx-auto`}>
        <div className="image-bg">
          <Web3ModalProvider>
            <Navbar />
            {/* <Navbar />
          <Sidebar /> */}
            {children}
          </Web3ModalProvider>
        </div>
      </body>
    </html>
  )
}
